# Generated by Django 5.2.5 on 2025-08-12 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WHATSAPP"),
                            ("sms", "SMS"),
                            ("web", "WEB"),
                        ],
                        default="whatsapp",
                        max_length=50,
                    ),
                ),
                ("external_id", models.CharField(max_length=128, unique=True)),
                ("sender", models.CharField(max_length=128)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("booking_inquiry", "Booking Inquiry"),
                            ("checkin_help", "Check-in Help"),
                            ("payment_issue", "Payment Issue"),
                            ("complaint", "Complaint"),
                            ("chit_chat", "Chit Chat"),
                        ],
                        max_length=64,
                    ),
                ),
                ("intent_conf", models.FloatField()),
                ("sentiment", models.CharField(max_length=16)),
                ("sentiment_score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediction",
                        to="inbox_ai.message",
                    ),
                ),
            ],
        ),
    ]
